"""bcrypt password helpers — must stay verify-compatible with passlib hashes."""
from __future__ import annotations

from app.services.auth.passwords import hash_password, verify_password

# Generated by the previous passlib[bcrypt] CryptContext for "demo". Existing
# DB rows hold hashes like this; verify_password must keep accepting them.
_PASSLIB_HASH_FOR_DEMO = "$2b$12$A8xsyM9ACPXgItr4VJeSb.rjjTWQo0ibFLLCPFWip9iAB5yD.AzzK"


def test_roundtrip():
    h = hash_password("correct horse battery staple")
    assert h.startswith("$2b$")
    assert verify_password("correct horse battery staple", h)
    assert not verify_password("wrong password", h)


def test_verifies_legacy_passlib_hash():
    assert verify_password("demo", _PASSLIB_HASH_FOR_DEMO)
    assert not verify_password("not-demo", _PASSLIB_HASH_FOR_DEMO)


def test_long_passwords_truncate_like_passlib():
    # bcrypt only uses the first 72 bytes; two passwords identical in that
    # prefix must verify against each other's hash (passlib behaved this way).
    base = "x" * 72
    h = hash_password(base + "AAAA")
    assert verify_password(base + "BBBB", h)


def test_malformed_hash_returns_false():
    assert not verify_password("anything", "not-a-bcrypt-hash")
    assert not verify_password("anything", "")
    assert not verify_password("anything", None)
